vich_uploader:
  db_driver: orm

  mappings:
    category_image:
      uri_prefix: /images/categories
      upload_destination: "%kernel.project_dir%/assets/img/cat"
      #namer: Vich\UploaderBundle\Naming\UniqidNamer
    pictogram_image:
      uri_prefix: /images/pictograms
      upload_destination: "%kernel.project_dir%/assets/img/picto"
      #namer: Vich\UploaderBundle\Naming\UniqidNamer
      #namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
